# Generated by Django 4.0.4 on 2022-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('book_code', models.IntegerField()),
                ('auther', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'book_library',
            },
        ),
    ]
